-- =============================================================
-- V1 - Esquema inicial de EnergiAI
-- Flyway es el dueño del esquema; Hibernate corre con ddl-auto=none.
-- Tipos y nombres de columna alineados con las entidades JPA.
-- =============================================================

CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    nombre        VARCHAR(255),
    auth_provider VARCHAR(255) NOT NULL,
    provider_id   VARCHAR(255),
    creado_en     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE factura (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumo_kwh                  INTEGER NOT NULL,
    uso_horario_pico             BOOLEAN NOT NULL,
    cantidad_equipos             INTEGER NOT NULL,
    tipo_inmueble                VARCHAR(255) NOT NULL,
    horas_alto_consumo           DOUBLE PRECISION NOT NULL,
    area_inmueble                DOUBLE PRECISION,
    numero_personas              INTEGER,
    tiene_aire_acondicionado     BOOLEAN,
    tiene_calentador_electrico   BOOLEAN,
    tiene_iluminacion_led        BOOLEAN,
    antiguedad_electrodomesticos VARCHAR(255),
    tarifa_electrica             DOUBLE PRECISION
);

CREATE TABLE analisis (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id             BIGINT,
    factura_id             BIGINT NOT NULL,
    categoria              VARCHAR(255) NOT NULL,
    probabilidad           DOUBLE PRECISION NOT NULL,
    costo_estimado_mensual DOUBLE PRECISION NOT NULL,
    indice_eficiencia      DOUBLE PRECISION,
    modelo_version         VARCHAR(255),
    fuente_clasificacion   VARCHAR(255),
    creado_en              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_analisis_factura UNIQUE (factura_id),
    CONSTRAINT fk_analisis_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT fk_analisis_factura FOREIGN KEY (factura_id) REFERENCES factura (id)
);

CREATE TABLE analisis_recomendacion (
    analisis_id BIGINT NOT NULL,
    texto       VARCHAR(500),
    CONSTRAINT fk_recomendacion_analisis FOREIGN KEY (analisis_id) REFERENCES analisis (id)
);

CREATE INDEX idx_analisis_usuario ON analisis (usuario_id);
CREATE INDEX idx_recomendacion_analisis ON analisis_recomendacion (analisis_id);
